# Generated by Django 3.1 on 2020-09-18 19:04

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetic', models.BooleanField()),
                ('cancer_patient', models.BooleanField()),
                ('cardiac_patient', models.BooleanField()),
                ('asthama_patient', models.BooleanField()),
                ('blood_pressure_patient', models.BooleanField()),
                ('weak_immunity', models.BooleanField()),
                ('other', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healthinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergencycontacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('temp', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.DecimalValidator(decimal_places=1, max_digits=4)])),
                ('headache', models.BooleanField()),
                ('running_nose', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('loss_smell_taste', models.BooleanField()),
                ('difficulty_breathing', models.BooleanField()),
                ('oxygen_level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0, 'To low value'), django.core.validators.MaxValueValidator(100, 'Might be incorrect')])),
                ('travel', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basicinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
