# Generated by Django 3.1.1 on 2020-10-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontacts',
            name='contact',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
