# Generated by Django 3.1.1 on 2020-11-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytracker', '0002_auto_20201024_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontacts',
            name='contact',
            field=models.EmailField(max_length=254),
        ),
    ]
